# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd3c6698cbcc1d8406fb31d0de06d0fd2900cfdfdcf2ff9e04c6af986414ae77115902d0d24c9d9fef5fa18013f6fc8dfdc95fc027252639a0e517a49dc2131b

test:
  secret_key_base: 28133ba50e056fc58926a620d8f5aa87b4f6f25993a0fb9c0591319d776115d985f4975a58201e03b69dd152c95f70d5869bbbf4572371230ea9a3116eadb8f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
